### ISSUE TITLE
jbundler fails on Windows 10 (NoMethodError)

### ISSUE THREAD

**Issue by rosenjcb** [mkristian/jbundler#88]
jbundler seems to fail to install dependencies (using the command `jruby -S jbundle install`) on Windows 10. I've encountered this error even with a simple 1 line JARFILE in an empty directory. This is the error I get:

```
c:/jruby-9.2.0.0/lib/ruby/stdlib/monitor.rb:256: warning: toplevel constant Mutex referenced by Thread::Mutex
NoMethodError: undefined method `extra_gem_paths' for JRuby::Util:Module
  spec_directories_from_classpath at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:97
                             dirs at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:70
                        stubs_for at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/specification.rb:869
                   matching_specs at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:279
                         to_specs at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:302
                          to_spec at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:322
                              gem at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:65
                          require at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:47
                            <top> at uri:classloader:/maven/tools/dsl.rb:1
                          require at org/jruby/RubyKernel.java:944
                           (root) at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
                            <top> at c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
[ERROR] Internal error: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `extra_gem_paths' for JRuby::Util:Module -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `extra_gem_paths' for JRuby::Util:Module
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `extra_gem_paths' for JRuby::Util:Module
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1307)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1352)
        at org.sonatype.maven.polyglot.ruby.RubyParser.<init>(RubyParser.java:42)
        at org.sonatype.maven.polyglot.ruby.RubyModelReader.read(RubyModelReader.java:56)
        at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:143)
        at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:95)
        at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:273)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
        at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
        at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
        at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
        at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `extra_gem_paths' for JRuby::Util:Module
        at RUBY.spec_directories_from_classpath(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:97)
        at RUBY.dirs(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:70)
        at RUBY.stubs_for(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/specification.rb:869)
        at RUBY.matching_specs(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:279)
        at RUBY.to_specs(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:302)
        at RUBY.to_spec(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/dependency.rb:322)
        at RUBY.gem(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_gem.rb:65)
        at RUBY.require(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:47)
        at RUBY.<top>(uri:classloader:/maven/tools/dsl.rb:1)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:944)
        at RUBY.(root)(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at RUBY.<top>(c:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
Errno::ENOENT: No such file or directory - C:/Users/rosen/desktop/test/pkg/dependencies.txt
               sysopen at org/jruby/RubyIO.java:1258
                  read at org/jruby/RubyIO.java:3807
  install_dependencies at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/lock_down.rb:113
             lock_down at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/lock_down.rb:54
               install at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/lib/jbundler/cli.rb:80
                   run at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/command.rb:27
        invoke_command at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
              dispatch at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor.rb:387
                 start at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/bundler-1.16.3/lib/bundler/vendor/thor/lib/thor/base.rb:466
                <main> at C:/jruby-9.2.0.0/lib/ruby/gems/shared/gems/jbundler-0.9.3/bin/jbundle:47
                  load at org/jruby/RubyKernel.java:994
                <main> at C:/jruby-9.2.0.0/bin/jbundle:23
```

It may be an env issue, but I'm not too sure.

**Comment by enebo** [comment]
@mkristian I also tried this on win10 but I did not have any issues with a minimal example.  We both are using win10, jruby installer install, java 8, latest version of maven.

@rosenjcb also nuked his .m2/repository.  He uninstalled and reinstall jruby.

I suspect and env inssue because we have same OS, same jruby, same maven, and same java.  Any ideas?

**Comment by mkristian** [comment]
I just look around a bit. the error says in can not find the method used here:

https://github.com/jruby/jruby/blob/master/lib/ruby/stdlib/rubygems/defaults/jruby.rb#L97

it actually runs out of maven which uses jruby from classloader but the error also states the it uses jruby from c:/jruby-9.2.0.0/

JRUBY_HOME env  maybe

**Comment by rosenjcb** [comment]
@mkristian 

My JRUBY_HOME environmental variable is set to "c:\jruby-9.2.0.0"

**Comment by enebo** [comment]
@rosenjcb @mkristian I can confirm I do not explicitly set JRUBY_HOME as an env.

**Comment by mkristian** [comment]
@rosenjcb could try to unset this and try again executing this ?

**Comment by rosenjcb** [comment]
Deleting the JRUBY_HOME environmental var seems to have fixed it. Thank you!

**Comment by enebo** [comment]
@mkristian maybe protect against this in a future release?

**Comment by mkristian** [comment]
if this is the root of the problem I need to see to get this maven execution to unset this env somehow. @enebo yes I will

**Comment by enebo** [comment]
@mkristian thanks.  we tried so many things and it was under our noses the whole time!

**Comment by mkristian** [comment]
@enebo happy that I could help but it was your first comment which made me see this c:/jruby-9.2.0.0 in the error message
:)
